# Config file for automatic testing at travis-ci.org

language: python

install:
  - pip install coveralls flake8

python:
  - "2.7"

# command to install dependencies and run tests
script:
  # Run the tests first, and if they pass look at for style guide problems.
  - coverage run --source=bootstrap_salt setup.py test

  # If we are a Pull request, check the changes introduced in it for pep8
  #
  # Or if we are just on a branch, work out what we've changed since we
  # branched off master
  - |
    set -e -o pipefail;
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]
      then git diff $TRAVIS_COMMIT_RANGE | flake8 --diff;
      else git fetch -q origin master:origin/master && git diff origin/master... | flake8 --diff
    fi


after_success:
  coveralls
  
